server:
  port: 9005
  error:
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html   # 파일 확장자
    # TODO : 배포시 true 처리
    cache: false # default true 개발 시에는 false 로 두는게 좋다.
    enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/myshop;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

